<ol>
  <li><a href="/reason/english">english - REASON FOR HOPE</a><br>
  <li><a href="/reason/serbian">serbian - RAZLOG ZA NADU</a><br>
  <li><a href="/reason/croatian">croatian - RAZLOG ZA NADU</a><br>
  <li><a href="/reason/serbian-cyrillic">serbian-cyrillic - РАЗЛОГ ЗА НАДУ</a><br>
  <li><a href="/reason/serbo-croatian">serbo-croatian - RAZLOG ZA NADU</a><br>
  <li><a href="/reason/arabic">arabic - فكر أمل</a><br>
  <li><a href="/reason/dutch">dutch - AANLEIDING VOOR HOOPEN</a><br>
  <li><a href="/reason/french">french - RAISONNEZ POUR ESPOIR</a><br>
  <li><a href="/reason/german">german - SCHLUßFOLGERN SIE FÜR HOFFNUNG</a><br>
  <li><a href="/reason/greek">greek - ΛΟΓΟΣ ΓΙΑ ΤΗΝ ΕΛΠΙΔΑ</a><br>
  <li><a href="/reason/italian">italian - RAGIONI PER LA SPERANZA</a><br>
  <li><a href="/reason/norwegian">norwegian - RESONNER FOR HÅP</a><br>
  <li><a href="/reason/persian">persian - من مسن سالى من اج</a><br>
  <li><a href="/reason/polish">polish - POWÓD DLA UFAJĄ</a><br>
  <li><a href="/reason/portuguese">portuguese - ARGUMENTE PARA ESPERANÇA</a><br>
  <li><a href="/reason/russian">russian - ПРИЧИНА ДЛЯ НАДЕЖДЫ</a><br>
  <li><a href="/reason/turkish">turkish - Çıkarma umma</a><br>
  <li><a href="/reason/ukrainian">ukrainian - ПРИЧИНА ДЛЯ СПОДІВАННЯ</a><br>
  <li><a href="/reason/spanish">spanish - Razón para Hope</a><br>
  <li><a href="/reason/magyar">magyar - A reménység oka</a><br>
  <li><a href="/reason/philippine">philippine - RASON SA PAGLAOM</a><br>
    <!--
          <li><a href="swedish.htm">swedish - SKÄL FÖR HOPPNING</a><br>
          <li><a href="korean.htm">korean - &#55148;&#47581;&#51012;&#50948;&#54620;&#51060;&#50976;</a><br>
          -->
</ol>
