<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf8">
  <title><?= "Reason for hope :: {$language}" ?></title>
  <style>
    <!--
    p {
      text-align: justify;
      vertical-align: middle;
      text-indent: 3em;
      margin-bottom: 1em;
      margin-top: 1.5em;
    }

    body {
      font-family: Verdana, Arial, Helvetica, sans-serif;
      font-size: 12pt;
      text-align: justify;
      text-indent: 3em;
      vertical-align: middle;
      height: auto;
      width: auto;
      background-image: url(../images/art_bg.gif);
      left: 100pt;
      padding: 50px;
    }

    h2 {
      font-family: "Times New Roman", Times, serif;
      font-size: 18pt;
      font-weight: bold;
      text-align: left;
    }

    h1 {
      font-family: "Times New Roman", Times, serif;
      font-size: 28pt;
      font-weight: bold;
      color: #FF0033;
    }

    td {
      font-family: "Times New Roman", Times, serif;
      font-size: 18px;
      padding: 1em;
      height: auto;
      width: auto;
      text-align: justify;
      text-indent: 3em;
    }

    .normal {
      font-family: "Times New Roman", Times, serif;
      font-size: 14pt;
      text-indent: 2em;
      font-style: italic;

    }
    -->
  </style>
</head>
<body>
  <?= $contents ?>
  <?= $navigation ?>
</body>
</html>
