<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Reason for hope</title>
  <link href="../css/style.css" rel="stylesheet" type="text/css">
  <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <style>
      body {
          font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
          text-align: justify;
      }

      h1 {
          color: #719e40;
          letter-spacing: -3px;
          font-family: 'Lato', sans-serif;
          font-size: 100px;
          font-weight: 200;
          margin-bottom: 0;
      }
  </style>

</head>
<body>
<?= $contents ?>
<?= $books ?>
<?= $navigation ?>
</body>
</html>
